global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'inventory-easy-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'products-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['products-service:3001']
        labels:
          service: 'products'

  - job_name: 'stock-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['stock-service:3002']
        labels:
          service: 'stock'

  - job_name: 'suppliers-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['suppliers-service:3003']
        labels:
          service: 'suppliers'